[deps]
BAT = "c0cd4b16-88b7-57fa-983b-ab80aecada7e"
BayesHistogram = "000d9b38-65fe-4c81-bdb9-69f01f102479"
BinnedModels = "fa1fc709-16e9-4084-816c-4cfb0f07afb9"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FHist = "68837c9b-b678-4cd5-9925-8a54edc8f695"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MPGenbb = "8084c56b-e18a-4ca6-9b1f-448b6eff89cb"
MeasureBase = "fa1605e6-acd5-459c-a1e6-7e635759db14"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
PlutoStyles = "16e07271-a41c-4e3e-b73a-b807cf2ea0eb"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SNSensitivityEstimate = "4337d2dd-53cf-40a5-bc43-6e7cc5722bd2"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
UnROOT = "3cd96dde-e98d-4713-81e9-a4a1b0235ce9"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
